language: java
env:
  global:
  - secure: b3iOmfhDggB8oMkgTTDvRlfikbWLSmsV3HtJZvhveW8VHsW/FDC14ez0P1xPHwV5s34NNVI3Qp6YMtkfMfAUeFqkcF1aHgB/iBXAk70zyZiKJFvRRQAQIICdMucQ9AVsFiDwMpZIAHc6LYlKnf5Tb88vLN2BC1B86ZduMcr/CSqUDl4guuIdn8WSgYCDpuJlwVb+WmyC6p4I51gJsXVYQmYyCFi5hRnmU/rOBKZHeEJNuK0Hx7lsmssPiXl8JW6FGwsf+XfxQbO4JVvRSiredCRONAzUhzqjDVStviR4gND0kizFRBu+D5E4aXAFyI/+z6Pv1+/Y1qYAnOq6GqXEkTUT3GE1Tv+PCoIVWCz6/WzC3a9pAY4zyr/PDT//xiGS+L33rPzLuIB/N+8fyYQzrWYKBGX+QZlmaYeD5imtiOXIgEW9NN5i8s0jcf0GPhxMkXAVj/VyLttSEU2iFGsSCBrPQahy2S9tJ8FXqiPQO7cnJORAMv/eX8zEurS725WDKN0D/dfU6310p0/C+u0z/+9huBuJakUQ4YIh8FJPr9NIR05XQ5j/uZIWOz3LtQAysKJaovujYH9FO2QCYj2h7rJNp3IxOtscOUYErWJWRcfFy05jxP0bvNm1OstEYiKzcagv0Ld4DFM4d3UVW/AGiXgOEB/y84i6lSOg624FSBI=
  - secure: kldoq1byws+oYrScl/B3Ca+r8UMqGzwC/1bvb9vjXtjCPzm+r8XLTqlIiSm6cM4agBYpUUHyhZuZ8k2gpmUBmo2ghHy/VotoyUJDLdIkGGv93s1a3dXEp0NjbB6anLEDG2EJY/1GngYI0QAldzpbHnoK9cK5jyGT7az3VyidKL8iyGaEVSc+hgFlgkZM8YpsuNfwpOfhDnIH+p8KIPHrV/U9TqxpAbivVOsfs5JhHNdBJ5Rfa+x3HGYvb1e7qdp5UnDSSz7Brk3ldKl9CeaLdfj959+rvtXwdpctsLT4aOIjbHz9y0yOiwmKEmSEPu27DI9ToUWDaJK0dG0B1zQlu42UL9VyCC+Vmnr0j2J2wNm+IUywnck+naVv+XEsnq9cSE5Y2P8gPC0KfAIsfrM3rhh+8MnAukFcdFgqAoJFXpNZmrAaoaShQh4Ni0BfhgYBAO8h2UDr8OwKz/n+xhi+OqmNNRngXdecNGmEHQ2ew7pXAdc4bu8cqfmAkK+q3uOwRbpecNm53HAREHYdqbQOrNrRsGZcZljv+Sm8mvAY9z/SkBVIYgYaKlevWkxdAbZFC0RJu3mMBwWzFOY6WHL5IITzG4uCZn1bCIHU90e/x3KzLbJLMJTUMdljjspz4sn7LtLUdy1nq/jy0Ly3ZrAHEi53kmkzGZCvEZlunFoaf5A=
script: "mvn -B deploy -DskipTests -s mvnsettings.xml"
deploy:
  provider: releases
  api_key:
    secure: fHxdOfDeHyMwIwyuXWJ7YOxW1R5Dpp3K5UuA1HmNgdDiPuafoQbZL3qLy77/Y6DkbxTsshA3E6g0dzJG3+uZJ5/jTOTXlaOToU9IT3fcpRxbktqLDgAh/Rh5Lhd0KyIz6n9Y4bWIpm4AjZ13jrK0tC8mcEQ9PgZnY/5rW4/0rwKsn+2H7TzWydt97BAkCHOWqWIxOBEjbJSchnGOGGhpClupR7U07Xt3yIrSfzft0JsOuq6OBTK1MRldROf23N7nzAwe2IuqMD9/hQJbZ7MF86vmM4HzCbrMRgFsa1WCoOZZviZUPzqQDseJIgtu1oOVoJUZzMXGT+IglscIH39LzyMGmaxJJM+/2z+rPiGyExJlFSMCLczv7UFvBsTU0iJFJoyzbZMSN0cyJhLacO66kZRfVsx3Xk0JQ//RM43qDHerm7Ekgbye6vdHFfQ0JSuhJk4+W35G7O0uf8M2wo/SJ7rIyeYwrOcH7XikduyaaZovIJhRBvFC+x35DdYgfQ9GWuQmVO2GlqD4YL0Zi0ucKH+IoKXkRlbwxaDcbTe3BL2tb14iQJkY4QW6IKs5JgE2nSETWWlFAKqWgaGmqwK/+6m8sKq327zylIK61dss0tPet2ZK0ARwQCSORRCTaZc9K4fegNf2NuD1OYOYywHMZhH9tqwie0I6pOZgN5aPG0g=
  file_glob: true
  file:
    - "frontend/target/*.zip"
    - "module/target/*.zip"
    - "servlet/target/*.war"
  skip_cleanup: true
  prerelease: true
  on:
    repo: attivio/searchui
    branch: develop
