language: java
env:
  global:
  - secure: jcA9yhimyfAu3PiRipe+6+YXlikC4OJJa2sfAYqd6UMbyVS8tAjyHul1lVY03dK6vepiwQ8Q+1DGAiCg3jwONulVYNPkbEg4sZ2/NtU/N0ncK6v70CWwB2sgl9g+baTiH1nT9rjfPWxJF1FcqA4tIlmv5CPdjZitza6u00yqOZWGiAHQOufbF+ZZSq7bsxYx2buUX0tAeFTmTtwEtAFkoo0FdZEAtvTKwkYh+/wAkzrV7Srts+mXUiL5EmmqyGZZAe85KEsY3PwheeCNhAh5uFI4Cjo1RYxIFZyNi5+8X/N+qgcVSdPvwpbvh///zCLivK9R/GBZZgYYwAPlhfQjb06e8n7Gl6QKMOsccFwHDH3mfWX9VTRoahZfdy6Dr3vr260hysW4I8a7bgIsW9SYSfCHqpB0llko1AV5AjDAJ965G42TOUzeuZSlkIssS6ELSYcRbBAeZWXT0BnipkX5uFU4tisimoyXi0xaIXXnRQpVHy4R5cEaNgxj3sWv+8laeHIWw5icDEi9ea4sgr+1mNjC7Rwpu1lNsXY3FaaocdFBHGChwBp9lZuQ7CVW0vDq+LvKct411HmsNRagHJ4Wf5J+Ql01rsF01S14qUvlbgHBlGRdcRsZnC8wVtxfLHc4uVP5zCeI5IIeyRDlaYdo9J/n88dNJi73O5mAFCE+Bew=
  - secure: A/lTniVgrTWvFC384GNQhwpGSSVmY/eICXvdZ8G/L5h0pio88ocyR9YYGEpOvbVSouoMJTB0Ie1/6fFsnAa1NnjNWx6Ni8tZlbiys5mekyLjNoLRljJvqGaKhZKBkUlx/XmymVBzaEOSxbI41wA8DMjn38j1vgA/E+TKx7+x0ztEa5Xvdr4dB1MHErF3qb6JTqJJZfOBeKgYtAsDXymXxqNxkIPL0fk4H+AckLQ6YfKg8bQGTeuEXrAPCSGOdZKnMwNp0h5b/FjlcaFmcIWBHfGKB8kMpefCDpum0z3NuIsnwgEUuHxeGec05zOl4lI5NqfvFyxK0i8SjXNpb8iqQNJ7YGGsIv8NLjIJsqtRqkDSXC3SMIcZQRoW/7FdkxDmjT9ieIdjUr13ipqLLKlSMYdOxAalR26aBTKGNf8sOCedsNU9ZUCCuwgF3+wSZ/+5tMYERezk2wJdXCiCICRrXgWzwAxLqDNesFMPjN4yoRM5fcop0SdOqHOj+Hf0GyzYyZtan92Rou2PNEvH5dD82zAWMVLtMY3aApMD8IyQzLJNKlkCN2NaqoaWvWrNHI2X/oXg7YxLFDa9h13EU3FFTR/XNDbG2f77rdaG2hNarp6WKnbN/bIdfNeW4g1CfpKsmBvRr0QhB8pxbwV7WZ3wSRXXUzIhfFgnsi07TeHt77U=
script: mvn -B deploy -DskipTests -s mvnsettings.xml
deploy:
  provider: releases
  api_key:
    secure: Zgc9Zg1Al/NO5Ct2JOuE6K7Xg5qjU3kuVpWElRCZ9n31BTnQPwxhttdW4KSAtlxBG9ifpcIq99i5cvc+apLRyM0XYN3Ad8ujNU5yDlJibtYyHRD0JoiwwhYl8Jsd3YYNu/VuBHkeEeRFEu5ZkpJYnRnwWcHTcJqAQfVZO54b/L+T3rh7786OIZfGgsU3aLHf9dK5CvOVOYo4mXjY1+kpYjmqonRId3ln5yOJ1wMQHoupwEdrnyg13AvyFkn2CQ+UvlIyjqJ+SyKnUu694LnB+J6ztZhFD79kMj/OM2beLK0zJS+GBq66ge0JzuHgQoD4p93U5LBih6N4JNzaz72hb1mPPkGVMK+HFCk8apIlxL8i6r3IFsvNctRRhklQFBgqvLc22ZkNF5LldkNoA6mW3NoDIDMx2B/x7Xp2WgjrxaA6T4lvWkAMI1o4n4+ubeG8o24zGcP5+eq7wFT3rOWFR5qyoN+grvbUL1/3c6Vf83RH9TSynYLijgbAZHpzfT/DsD1bMmWpb8JtWj8iFtSG/BOGvKBHkqpUFqnFu26Wa6jukcmUo+6DoJieFto97yyLovGMxRYllk4OeogpmllCmvYw4zPEEYu5l9Ylsg741WgDEzABASXfFKwk4+7rW7f40hr2qmlsLgwy758NGCW6Pisla+eIlaGae9Fxbq8kFnw=
  file_glob: true
  file:
    - frontend/target/*.zip
    - module/target/*.zip
    - servlet/target/*.war
  skip_cleanup: true
  prerelease: true
  on:
    repo: attivio/searchui
    branch: develop
